name = "paradaux_site"
type = "webpack"
account_id = "38df507baff0cce8d7b17a60f4f4b1c9"
workers_dev = true
route = "paradaux.io/*"
zone_id = "679e734058ed0954fcc1e25fccaa9be8"

[site]
bucket = "./public"
